# Generated by Django 4.1.3 on 2022-12-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('artist', models.TextField()),
            ],
        ),
    ]
