# Generated by Django 4.1.3 on 2022-12-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_loved_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
